language: SystemVerilog
env:
  - TRAVIS_BUILD_DIR=/home/asad/workspace/TCD_workspace/Xilinx_mvau
before_script:
  - cd $TRAVIS_BUILD_DIR/Doc/natural_docs
script:
  - ./nd_gen.sh
  - cd ../../
deploy:
  provider: pages
  cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/Doc/api
  on:
    branch: master
