language: SystemVerilog
before_script:
  - cd $TRAVIS_BUILD_DIR/Doc/natural_docs
script:
  - ./nd_gen.sh
deploy:
  provider: pages
  cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/Doc/api
  on:
    branch: master
